# Generated by Django 3.2.12 on 2024-09-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='republic',
            name='community_type',
            field=models.CharField(choices=[('mista', 'Mista'), ('feminino', 'Feminino'), ('masculino', 'Masculino')], default='mista', max_length=20),
        ),
        migrations.AddField(
            model_name='republic',
            name='description',
            field=models.TextField(default='Descrição padrão da república'),
        ),
        migrations.AddField(
            model_name='republic',
            name='housing_type',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento')], default='casa', max_length=20),
        ),
        migrations.AddField(
            model_name='republic',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
