# Generated by Django 3.2.12 on 2024-09-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republic', '0002_auto_20240924_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='republic',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='republic',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='republic',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
