# Generated by Django 4.2.1 on 2023-05-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Republic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cellphone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('cuty', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Feminine'), ('MI', 'Mixed')], max_length=2)),
                ('num_vacancies', models.IntegerField()),
                ('created_in', models.DateField()),
            ],
        ),
    ]
