# Generated by Django 4.2.1 on 2023-05-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='republic',
            old_name='cuty',
            new_name='city',
        ),
    ]
