# Generated by Django 4.2.2 on 2023-06-26 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republic',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='republics_as_member', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='republic',
            name='payable_items',
            field=models.ManyToManyField(blank=True, to='unirep_app.payableitem', verbose_name='payable_items'),
        ),
    ]
