# Generated by Django 4.2.2 on 2023-06-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0002_alter_republic_members_alter_republic_payable_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payableitem',
            name='republic_id',
        ),
    ]
