# Generated by Django 4.2.1 on 2023-05-29 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0002_rename_cuty_republic_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_type', models.CharField(choices=[('1', 'Normal'), ('2', 'Admin')], max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('MA', 'Male'), ('FE', 'Feminine')], max_length=2)),
                ('cellphone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=200)),
                ('hobbie', models.CharField(max_length=200)),
                ('preference', models.CharField(max_length=200)),
                ('disgust', models.CharField(max_length=200)),
                ('created_in', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='republic',
            name='created_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='republic',
            name='num_vacancies',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PayableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('maturity_in', models.DateTimeField()),
                ('status', models.CharField(choices=[('1', 'Payable'), ('2', 'Paid')], max_length=1)),
                ('created_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('republic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unirep_app.republic')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unirep_app.user', verbose_name='user_id')),
            ],
        ),
        migrations.AddField(
            model_name='republic',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unirep_app.user', verbose_name='user_id'),
        ),
    ]
