# Generated by Django 4.2.1 on 2023-06-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0002_user_republic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republic',
            name='cellphone',
            field=models.CharField(max_length=15),
        ),
    ]
