# Generated by Django 4.2.1 on 2023-06-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0004_alter_republic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='republic',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
