# Generated by Django 4.2.1 on 2023-06-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0005_republic_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='republic',
            name='city',
        ),
        migrations.RemoveField(
            model_name='republic',
            name='district',
        ),
        migrations.RemoveField(
            model_name='republic',
            name='state',
        ),
        migrations.RemoveField(
            model_name='republic',
            name='zip_code',
        ),
    ]
