# Generated by Django 4.2.1 on 2023-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0006_remove_republic_city_remove_republic_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='republic',
            name='qtd_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
