# Generated by Django 4.2.1 on 2023-06-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0007_republic_qtd_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='republic',
            name='qtd_members',
        ),
        migrations.RemoveField(
            model_name='republic',
            name='value',
        ),
    ]
