# Generated by Django 4.2.1 on 2023-06-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0008_remove_republic_qtd_members_remove_republic_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='republic',
            name='qtd_members',
            field=models.IntegerField(default=0, verbose_name='qtd_members'),
        ),
    ]
