# Generated by Django 4.2.1 on 2023-06-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unirep_app', '0009_republic_qtd_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='republic',
            name='value',
            field=models.IntegerField(default=0, verbose_name='value'),
        ),
    ]
